name: Classroom Autograding

on: [push, pull_request]

jobs:
  autograding:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert

    - name: Convert notebook to script
      run: |
        jupyter nbconvert --to script Lab3.ipynb

    - name: Run autograding
      run: |
        # Ejecuta el script convertido
        python Lab3.py
        
        # Ejecuta las pruebas de autograding
        python test.py
