name: Classroom Autograding

on: [push, pull_request]

jobs:
  autograding:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert

    - name: Run autograding
      run: |
        # Convert the Jupyter notebook to HTML and execute it
        jupyter nbconvert --to notebook --execute --inplace Minimax_Tree_Games.ipynb
        
        # Convert the executed notebook to HTML for easier review
        jupyter nbconvert --to html Minimax_Tree_Games.ipynb --output Minimax_Tree_Games.html

        # Add additional steps here to validate outputs or compare against expected results
        # For example, using nbgrader or custom scripts for grading

    - name: Upload grading results
      uses: actions/upload-artifact@v2
      with:
        name: grading-results
        path: Minimax_Tree_Games.html
